import { describe, it, expect } from 'vitest';
import { PROVIDER_COMMANDS } from '../src/types.js';

// We test the command construction logic by verifying the patterns
// that sendInitial would produce for each purpose

const CODEX_CMD = PROVIDER_COMMANDS['codex'];

describe('sender purpose templates', () => {
  it('review: includes git diff, CAPABILITY_DIRECTIVE, REVIEW REQUEST', () => {
    const purpose = 'review';
    const base = 'main';
    const filePath = '/tmp/hive-tmux/codex-prompt.txt';
    const marker = '[HIVE_DONE:r1]';

    // Simulates buildOuterCommand output
    const expected = `${CODEX_CMD} "[REVIEW REQUEST]`;
    expect(expected).toContain('REVIEW REQUEST');
    expect(`git diff ${base}...HEAD`).toContain('git diff main...HEAD');
    expect(filePath).not.toContain('$(');
  });

  it('verify: includes git diff HEAD~1, VERIFY REQUEST', () => {
    const cmd = `git diff HEAD~1..HEAD`;
    expect(cmd).toContain('HEAD~1');
  });

  it('consensus: uses file path directly (template has DIRECTIVE)', () => {
    const filePath = '/tmp/hive-tmux/codex-prompt.txt';
    const cmd = `${CODEX_CMD} "${filePath}"`;
    expect(cmd).not.toContain('CAPABILITY_DIRECTIVE');
    expect(cmd).toContain(filePath);
  });

  it('implement: uses file path directly (template has full context)', () => {
    const filePath = '/tmp/hive-tmux/codex-prompt.txt';
    const cmd = `${CODEX_CMD} "${filePath}"`;
    expect(cmd).toContain(filePath);
  });

  it('outer command never contains user prompt content', () => {
    const dangerousPrompt = '$(rm -rf /) `evil` $HOME';
    const filePath = '/tmp/hive-tmux/codex-prompt.txt';
    const marker = '[HIVE_DONE:abc]';

    // review outer command: only contains static strings + filePath + marker
    const outerCmd = `${CODEX_CMD} "[REVIEW REQUEST]\ngit diff main...HEAD\n${filePath}\n${marker}"`;
    expect(outerCmd).not.toContain(dangerousPrompt);
    expect(outerCmd).not.toContain('rm -rf');
  });

  it('filePath is a fixed path generated by code, not user input', () => {
    const name = 'codex';
    const filePath = `/tmp/hive-tmux/${name}-prompt.txt`;
    // Path components are: static prefix + provider name + static suffix
    expect(filePath).toBe('/tmp/hive-tmux/codex-prompt.txt');
    expect(filePath).not.toContain(' ');
    expect(filePath).not.toContain('$');
  });
});
